export enum Env {
  PORT = "PORT",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD",
  DB_NAME = "DB_NAME",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",
  REDIS_DB = "REDIS_DB",
  PROJECT_NAME = "PROJECT_NAME",
  SIGNER_KEY = "SIGNER_KEY",
}
