import { SUPPORTED_CHAIN_IDS, SUPPORTED_CHAINS } from "./enum";

export const FETCHING_QUEUE = "fetching_queue";
export const ASSERTION_QUEUE = "assertion_queue";
export const EXECUTION_QUEUE = "execution_queue";
export const SAVE_TRANSACTION_JOB = "save_transactions_job";
export const BULL_BOARD_ROUTE = "/queues";

export const CONFIG_CACHE = "config";
export const REBASED_STRATEGIES_CACHE = "rebased_strategies";
export const BLACKLIST_STRATEGIES_CACHE = "blacklist_strategies";

export const DEFAULT_BLOCKS_PER_FETCH = 1;
export const DEFAULT_CALL_GAS_REQUIRED = 1_000_000;

export const CHAINID_MAPPING = {
  [SUPPORTED_CHAIN_IDS.ARBITRUM]: SUPPORTED_CHAINS.ARBITRUM,
  [SUPPORTED_CHAIN_IDS.BASE]: SUPPORTED_CHAINS.BASE,
  [SUPPORTED_CHAIN_IDS.BLAST]: SUPPORTED_CHAINS.BLAST,
  [SUPPORTED_CHAIN_IDS.BSC]: SUPPORTED_CHAINS.BSC,
  [SUPPORTED_CHAIN_IDS.LINEA]: SUPPORTED_CHAINS.LINEA,
  [SUPPORTED_CHAIN_IDS.MANTA]: SUPPORTED_CHAINS.MANTA,
  [SUPPORTED_CHAIN_IDS.MODE]: SUPPORTED_CHAINS.MODE,
  [SUPPORTED_CHAIN_IDS.OPTIMISM]: SUPPORTED_CHAINS.OPTIMISM,
  [SUPPORTED_CHAIN_IDS.POLYGON]: SUPPORTED_CHAINS.POLYGON,
  [SUPPORTED_CHAIN_IDS.SCROLL]: SUPPORTED_CHAINS.SCROLL,
  [SUPPORTED_CHAIN_IDS.ZKEVM]: SUPPORTED_CHAINS.ZKEVM,
};

export const BLACKLIST_STRATEGIES = [
  "0x0ab03be544b7e633d53dcf34bd5a3e7c44218769bb3e3757f144d414deef06de",
];
